# python CircleCI 2.0 configuration file
#every config.yml file starts with the CIrcleCI version number
version: 2
# jobs are a single execution of the build and are defined by a collection of steps
# if you have only one job it must be called build
jobs:
  # build is the name  of the job
  build:
    # the steps of a job occur in an enivronment are called an executor 
    # the common executor in CircleCI is a docker container
    docker:
    # the docker image which is linux with python 3,7 preinstalled
      - image: circleci/python:3.7
    
    #the working directory has to be checked out somewhere on the build
    working_directory: ~/repo
    
    #this key is where the list of steps for the job starts
    steps:
    #Step 1: obtain repo from github
    # check the source code out to the working directory for CI
    - checkout:
    # Step 2: create virtual env and install dependencies
    # executing command line programs or commands is done inside the run key
    - run:
    	# name stores every step of the build
        name: install dependencies
        # the | symbol specifies that what follow is a literal set of commands,
        # one per line just like a bash script
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    # Step 3 run linter and tests
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          flake8 --exclude=venv* --statistics
          pytest -v --cov=calculator
         `
